### ISSUE TITLE
Potentially Incorrect Labels for linear Model Prediction (train-Test Split)

### ISSUE THREAD

**Issue by abroniewski** [juanitorduz/juanitorduz.github.io#8]
I think the label's for these 2 visual's might need to be switched, as (I think) the `mean_pred` is representing `obs_pred` and vice-versa.
https://github.com/juanitorduz/juanitorduz.github.io/blob/8b1dab89a497504791117ff4c5f64cd6df167d21/lm_viz/index.html#L538
https://github.com/juanitorduz/juanitorduz.github.io/blob/8b1dab89a497504791117ff4c5f64cd6df167d21/lm_viz/index.html#L548

**Comment by juanitorduz** [comment]
Hey! Thank you for pointing this out! I will correct it :)
